services:
  fretefy.test.webapi:
    image: fretefy.test.webapi
    build:
      context: .
      dockerfile: Fretefy.Test.WebApi/Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ./Fretefy.Test.WebApi/Data:/app/Data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  ef:
    image: mcr.microsoft.com/dotnet/sdk:3.1
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: [ "tail", "-f", "/dev/null" ]